Домашнее задание

Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).


In [2]:
import numpy as np

In [39]:
x = int(input('Введите число N '))
def array_n_0(x):
    a = []
    for _ in range(x-1, -1, -1):
        a.append(_)
    return np.array(a)

array_n_0(x)  

Введите число N 7


array([6, 5, 4, 3, 2, 1, 0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.


In [35]:
n = int(input('Введите число N '))
def matrix_n_0(n):
    
    return np.diag(np.arange(n, -1, -1), k=0)
    # return np.array(np.arange(n, -1, -1), k=0) любое из двух

matrix_n_0(n)    

Введите число N 6


array([[6, 0, 0, 0, 0, 0, 0],
       [0, 5, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [37]:
#Зная что матрица состоит из нулей и элементов главной диагонали, достаточно посчитать сумму всех эелементов
#или элементов не равных 0
total = 0
for row in np.diag(np.arange(n, -1, -1), k=0):
    for elements in row:
        if elements != 0:
            total += elements
            
print(total)


21


Задание 3
Решите систему уравнений:
4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [10]:
a = ( [4., 2., 1.], [1., 2., 0.], [0., 5., 4.] )
a = np.array(a)
b = np.array([4., 12., -3])

In [12]:
from numpy import linalg

linalg.solve(a, b)

array([ 0.06896552,  5.96551724, -8.20689655])

In [ ]:
np.allclose( np.dot(a, linalg.solve(a, b)), b ) #Проверка

Задание 4
В материалах занятия раздел “Задача 4 домашнего задания”

In [42]:
import matplotlib.pyplot as plt

In [ ]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [ ]:
# угол между векторами в градусах

np.arccos( cosine( a, b ) ) * 360 / 2 / np.pi

In [ ]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [ ]:
#так как ID совподает с порядковыми номерами можно создать список куда поочередно добавить значения углов
shop = []

for raw in users_stats:
   
    shop.append(np.arccos( cosine( raw , next_user_stats ) ) * 360 / 2 / np.pi)
print(shop.index(min(shop)) + 1) #так как отсчет начинается в питоне с 0